Add support for parsing numbers according to JSON format
fastfloat/fast_float pull request #220
Opened 2023-09-14 01:30 UTC by mayawarrier

Details on the format are available here:
https://datatracker.ietf.org/doc/html/rfc8259#section-6

2023-09-14 04:04 UTC, lemire commented
Looks like a good idea. I will review and I expect to merge.

2023-09-14 14:23 UTC, lemire commented on tests/json_fmt.cpp
> +  const std::vector<double> expected{ -0.2, 0.02, 0.002, 1., 0. };
Both 1. and 0. are fine, but my expectation is that you could use 1 and 0. (This is not a request for you to change the code, just a comment.)

2023-09-14 14:33 UTC, lemire commented
@mayawarrier I think that the JSON format does not allow a leading `+`... only in the exponent, so `1e+1` is ok, but `+1e1` is not.

2023-09-14 14:34 UTC, lemire requested changes
It is not clear that this code disallows leading pluses, and I think it should.

2023-09-14 22:16 UTC, mayawarrier commented
> @mayawarrier I think that the JSON format does not allow a leading `+`... only in the exponent, so `1e+1` is ok, but `+1e1` is not.

Ok, I'll just ignore the FASTFLOAT_ALLOWS_LEADING_PLUS macro when the runtime format is json.

2023-09-15 01:18 UTC, mayawarrier commented
I disallowed leading pluses as requested. I also added an option to allow inf/nan in JSON mode. This is a common option in JSON parsers despite not being part of the standard.

2023-09-15 13:16 UTC, lemire commented
I am sure that this could be perfected, but it looks solid to me, merging.

2023-09-15 13:18 UTC, merged